# Generated by Django 4.2.2 on 2023-06-29 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TradeSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=50)),
                ('buy', models.BooleanField(default=False)),
                ('sell', models.BooleanField(default=False)),
                ('close_button_visible', models.BooleanField(default=False)),
                ('take_profit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stop_loss', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
