# Generated by Django 4.2.2 on 2023-06-29 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradesignal',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
