# Generated by Django 4.2.2 on 2023-06-29 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_alter_tradesignal_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradesignal',
            name='entry_price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tradesignal',
            name='stop_loss_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tradesignal',
            name='take_profit_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tradesignal',
            name='trade_now_visible',
            field=models.BooleanField(default=False),
        ),
    ]
