# Generated by Django 4.2.2 on 2023-06-29 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0004_tradesignal_entry_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradesignal',
            name='entry_price_visible',
            field=models.BooleanField(default=False),
        ),
    ]
