# Generated by Django 4.2.2 on 2023-06-29 15:04

from django.db import migrations, models
import trade.models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0005_tradesignal_entry_price_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradesignal',
            name='created_at',
            field=models.DateTimeField(default=trade.models.default_created_at),
        ),
    ]
