# Generated by Django 4.2.2 on 2023-06-29 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0006_tradesignal_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradesignal',
            name='entry_price',
            field=models.DecimalField(decimal_places=16, default=None, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='tradesignal',
            name='stop_loss',
            field=models.DecimalField(decimal_places=16, default=None, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='tradesignal',
            name='take_profit',
            field=models.DecimalField(decimal_places=16, default=None, max_digits=20, null=True),
        ),
    ]
