# Generated by Django 4.2.2 on 2023-06-30 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0010_alter_tradesignal_entry_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradesignal',
            name='category',
            field=models.CharField(choices=[('forex', 'Forex'), ('stock', 'Stock'), ('cryptocurrency', 'Cryptocurrency')], default='forex', max_length=20),
        ),
    ]
