# Generated by Django 4.2.2 on 2023-07-01 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0011_tradesignal_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradesignal',
            name='stop_loss',
            field=models.DecimalField(decimal_places=10, default=None, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='tradesignal',
            name='take_profit',
            field=models.DecimalField(decimal_places=10, default=None, max_digits=20, null=True),
        ),
    ]
